spring:
  application:
    name: discovery-service
  config:
    activate:
      on-profile: peer1
eureka:
  instance:
    hostname: peer1
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/, http://peer3:8763/eureka/
server:
  port: ${PORT:8761}

---

spring:
  application:
    name: discovery-service
  config:
    activate:
      on-profile: peer2
eureka:
  instance:
    hostname: peer2
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/, http://peer3:8763/eureka/
server:
  port: ${PORT:8762}

---

spring:
  application:
    name: discovery-service
  config:
    activate:
      on-profile: peer3
eureka:
  instance:
    hostname: peer3
    metadataMap:
      zone: zone3
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
server:
  port: ${PORT:8763}